name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Build Docker image
        run: |
          docker build -t myfastapiapp .

      - name: Save Docker image as artifact
        run: |
          docker save myfastapiapp > myfastapiapp.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: myfastapiapp
          path: ./myfastapiapp.tar
